name: Unzip File Example

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          mkdir -p extracted
          unzip path/to/Dashboard Visualisasi Peternakan Ayam Petelur.zip -d extracted/
